name: CI
run-name: "CI (${{ github.event_name }}) on ${{ github.ref_name }} by @${{ github.actor }}"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    uses: otfabric/.github/.github/workflows/go-ci.yml@v1
    with:
      codecov-name: go-tpkt
    secrets: inherit